### ISSUE TITLE
More flexible plugin installation

### ISSUE THREAD

**Issue by ThePixelDeveloper** [ICTO/ansible-elasticsearch#2]
Testing this out.

In the variables file:

``` yaml
  plugins:
    -
      name: 'karmi/elasticsearch-paramedic'
      creates: '/usr/share/elasticsearch/plugins/paramedic'
    -
      name: 'elasticsearch/elasticsearch-river-twitter/1.3.0'
      creates: '/usr/share/elasticsearch/plugins/river-twitter'
```

In the tasks:

``` yaml
# Install Elasticsearch plugins
- name: "Installing plugins"
  command: ${elasticsearch.plugin} -install {{ item.name }} creates={{ item.creates }}
  tags:
    - plugins
  with_items: ${elasticsearch.plugins}
```

This allows you to get rid of the paramedic vars and tasks files and adds a bit more flexibility for the user.
